-- Q1 What is the total revenue generated by male vs female customers?

SELECT gender, sum(purchase_amount) as revenue_generated 
FROM shopping_data
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM shopping_data
WHERE discount_applied = "Yes" and purchase_amount > (SELECT avg(purchase_amount) FROM shopping_data);

-- Q3. What are the top 5 products with the highest average rating?

SELECT
    item_purchased,
    ROUND(AVG(review_rating),2) AS avg_rating
FROM shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between Standard & Express shipping.

SELECT shipping_type, AVG(purchase_amount) as avg_purchase_amount
FROM shopping_data 
WHERE shipping_type in ("Express","Standard")
GROUP BY shipping_type;

-- Q5. DO subscribed customers spend more? Compare the average spend & total revenue 
-- between subscribers and non-subscribers.

SELECT subscription_status, COUNT(customer_id) as Total_customers,
			AVG(purchase_amount) as average_spend,
			SUM(purchase_amount) as total_revenue
FROM shopping_data 
WHERE subscription_status in ("YES","NO")
GROUP BY subscription_status
ORDER BY total_revenue, average_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased , 
Round(SUM(CASE WHEN discount_applied = "YES" THEN 1 ELSE 0 END)/count(*)*100 ,2) as discount_applied_pct
FROM shopping_data 
GROUP BY item_purchased
ORDER BY discount_applied_pct desc
limit 5;

-- Q7. Segment customers into New, Returning and loyal based upon their
-- total no of previous purchases and show the count of each segment.

WITH customer_type as (
SELECT *, CASE
		WHEN previous_purchases = 1 THEN "New"
        WHEN previous_purchases BETWEEN 2 AND 10  THEN "Returning"
        ELSE  "Loyal"
        END AS customer_segment 
FROM shopping_data
)
SELECT  customer_segment, count(customer_segment) as segment_count
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 products in each catagory?

WITH cte1 as (
SELECT category, item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() OVER( partition by category order by count(customer_id) desc) as item_rank
FROM shopping_data
GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_orders, item_rank
FROM cte1
WHERE item_rank < 4;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) likely to subscribe?

WITH repeat_buyers AS (
    SELECT customer_id, subscription_status
    FROM shopping_data
    WHERE previous_purchases > 5
)
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers,
    ROUND(COUNT(customer_id) * 100 / SUM(COUNT(customer_id)) OVER (),2) AS pct
FROM repeat_buyers
GROUP BY subscription_status;

-- Q10. What is the revenue contibution of each age group?

SELECT age_group, sum(purchase_amount) as revenue_contribution
FROM shopping_data
GROUP BY age_group
ORDER BY revenue_contribution desc;



